version: "3.7"
services:
  app:
    build:
      args:
        user: teste
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: teste_app
    container_name: teste_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - teste_app

  db:
    image: mysql:5.7
    container_name: teste_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - teste_app

  nginx:
    image: nginx:1.17-alpine
    container_name: teste_nginx
    restart: unless-stopped
    ports:
      - 8010:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - teste_app

networks:
  teste_app:
    driver: bridge